name: Test with Kind

on: push

env:
  KIND_VERSION: v0.20.0
  K8S_VERSION: v1.29.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Lint
        run: |
          gofmt -l -s $(find . -type f -name '*.go')
          if [[ -n $(gofmt -l -s $(find . -type f -name '*.go')) ]]; then exit 1; fi

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/${{ env.KIND_VERSION }}/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create kind cluster
        run: |
          kind create cluster --image kindest/node:${K8S_VERSION}

      - name: Set up kubectl
        run: |
          kubectl cluster-info --context kind-kind
          kubectl get nodes

      - name: Build and test
        run: |
          make build
          make test

      - name: Run a single focused test
        run: |
          bin/hydrophone --focus 'Simple pod should contain last line of the log' --output-dir ${{ github.workspace }}/results/

      - name: Archive conformance results
        uses: actions/upload-artifact@v3
        with:
          name: conformance-results
          path: ${{ github.workspace }}/results/